## Assignment 2 
### Ajay Choudhury (18018) &middot; BS 2018 EECS
### Due Date: 26 September 2021, Sunday, 11.00 am

### Example: Basic Numpy

(1) Create a NumPy array with the integers from your birthdate (year,
    month, and day)

(2) Retrieve the year.

(3) Replace the year with the current year.

(4) Create a NumPy array containing every 3rd number from 567 to 890. What is the 8th number in this array?  What is the 15th?

In [2]:
import numpy as np

In [3]:
# 1
a = np.array([1986, 12, 24])

In [4]:
# 2
a[0]

1986

In [5]:
# 3
a[0] = 2021

In [6]:
# 4
a= np.arange(567, 890, 3)
a

array([567, 570, 573, 576, 579, 582, 585, 588, 591, 594, 597, 600, 603,
       606, 609, 612, 615, 618, 621, 624, 627, 630, 633, 636, 639, 642,
       645, 648, 651, 654, 657, 660, 663, 666, 669, 672, 675, 678, 681,
       684, 687, 690, 693, 696, 699, 702, 705, 708, 711, 714, 717, 720,
       723, 726, 729, 732, 735, 738, 741, 744, 747, 750, 753, 756, 759,
       762, 765, 768, 771, 774, 777, 780, 783, 786, 789, 792, 795, 798,
       801, 804, 807, 810, 813, 816, 819, 822, 825, 828, 831, 834, 837,
       840, 843, 846, 849, 852, 855, 858, 861, 864, 867, 870, 873, 876,
       879, 882, 885, 888])

In [7]:
a[8]

591

In [8]:
a[15]

612

### Exercise 1 Basic Numpy

(1) Create an array of 10 random integers, from 0-100.

(2) Find the mean and standard deviation of these numbers.  

(3) Create another array of 10 random integers, from 0-100.

(4) Create a new array whose elements are the average of those from
    each of the previous ones.  

(5) Create an array of 10 random floats, from 0-100.

(6) We would expect the mean to be approaximately 50.  Is it?  What's
    the standard deviation?

(7) What are the min and max values?

In [58]:
numArray = np.random.randint(0, 100, 10)
print(numArray)

# mean
meanArray = numArray.mean()
print(meanArray)

# standard deviation
stdArray = numArray.std()
print(stdArray)

# another array
numArray2 = np.random.randint(0, 100, 10)
print(numArray2)

# array of averages
avgArray = np.array([meanArray, numArray2.mean()])
print(avgArray)

# array of random floats
floatArray = np.random.rand(10) *100
print(floatArray)

# mean and standard deviation
floatMean = floatArray.mean()
print(floatMean)
floatStd = floatArray.std()
print(floatStd)

# min and max values
floatMin = floatArray.min()
print(floatMin)
floatMax = floatArray.max()
print(floatMax)


[92 87 96 98 62  1 95 64  7 52]
65.4
34.35171029221107
[89 34 61 65 56 98 58 76 71 78]
[65.4 68.6]
[21.82610734 67.55824581 60.52398523 11.22026301 39.47377178  9.73702384
 24.9136568  90.60543408 96.44754742 95.54087967]
51.784691495782035
33.05482151867776
9.737023836564894
96.44754741541014


### Exercise 2 Indexing

(1) Create an array of 20 random integers from 0 to 100.

(2) Find the largest even number.

(3) Find the mean of the odd numbers.

(4) Create a NumPy array from the first and last odd numbers.

(5) Create an array of 20 floats from 0-1,000.

(6) Find the items that are less than the mean.

(7) Find the items less than mean-std.

In [90]:
arr = np.random.randint(0, 100, 20)
print(arr)

# largest even number
largestEven = arr[arr % 2 == 0].max()
print(largestEven)

# mean of odd
meanOdd = arr[arr % 2 != 0].mean()
print(meanOdd)

# array from first and last odd numbers
oddArray = arr[arr % 2 == 1][[0, -1]]
print(oddArray)

# float array 0-1000
floatArr = np.random.rand(20) * 1000
print(floatArr)
# print("\n")

# items less than mean
lessMean = floatArr[floatArr < floatArr.mean()]
print(lessMean)
# print("\n")

# less than mean-std
lessMStd = floatArr[floatArr < (floatArr.mean() - floatArr.std())]
print(lessMStd)


[37 83 54 28 30  2 64 85 31  4 74 11 80 21  5 45 44 18 53 71]
80
44.2
[37 71]
[ 46.89023873  47.47489808 694.632358   612.66806401 875.99837675
 407.30096774 528.3949342  140.18989125 106.88213274 818.43663767
 750.24682908 651.63504096  90.80000393 854.89911408 971.77679676
 776.21453223 980.99486902 846.33453592 377.21606522  41.3109893 ]
[ 46.89023873  47.47489808 407.30096774 528.3949342  140.18989125
 106.88213274  90.80000393 377.21606522  41.3109893 ]
[ 46.89023873  47.47489808 140.18989125 106.88213274  90.80000393
  41.3109893 ]


### Exercise 3 More indexing

(1) Create a NumPy array of 20 random integers from 0-100.

(2) What's the smallest even number greater than the mean?

(3) Show all numbers either < mean-std OR > mean+std.

(4) Show odd numbers < mean and even numbers > mean.

In [119]:
arr = np.random.randint(0, 100, 20)
print(arr)
# print("\n")

# smallest even number greater than mean
try:
    evenMin = arr[(arr % 2 == 0) & (arr > arr.mean())].min()
    print(evenMin)
except:
    print("Even number greater than mean doesn't exist.")

# either less than mean-std OR greater than mean+std
thirdPart = arr[(arr < (arr.mean() - arr.std())) |
                (arr > (arr.mean() + arr.std()))]
print(thirdPart)

# odd numbers < mean and even numbers > mean
fourthPart = arr[((arr % 2 != 0) & (arr < arr.mean())) |
                 ((arr % 2 == 0) & (arr > arr.mean()))]
print(fourthPart)


[73 32 20 67 35 51 41 19 49 81 11 92  9 76 44 78  4 23 74 47]
74
[73 19 81 11 92  9 76 78  4 74]
46.3
[35 41 19 11 92  9 76 78 23 74]


### Exercise 4 Assigning via indexes

(1) Create a NumPy array of 40 random integers, from 0-100.

(2) Find all numbers that are within 1 standard deviation of the mean,
    and set them to be equal to the mean.  Has the mean changed?  Has
    the std changed?

(3) Create another NumPy array of 10 random integers, from 0-100.

(4) Set the item at the even indexes to be equal to the items at the odd
    indexes.  So index 0 will get the value at index 1, etc.


In [242]:
arr = np.random.randint(0, 100, 40)
print(arr)
print(arr.mean())
print(arr.std())

# second part
arr[(arr >= arr.mean() - arr.std()) & (arr <= arr.mean() + arr.std())] = arr.mean()
print(arr)
print(arr.mean())
print(arr.std())
# The mean and the standard deviation gets changed

# 10 random integers 0-100
arr2 = np.random.randint(0, 100, 10)
print(arr2)

# set items at even places with the values of those at odd position
arr2[np.arange(0, 10, 2)] = arr2[np.arange(1, 10, 2)]
print(arr2)

[13 92 73 21 13 23 34 22 82 57 65 11 70 66 99 67 17 38 50  9 86 30 41 97
 13 74  5 76 99 67  0 64 31 13 31 30 31 48 52 67]
46.925
28.943382231522286
[13 92 46 46 13 46 46 46 82 46 46 11 46 46 99 46 17 46 46  9 86 46 46 97
 13 46  5 76 99 46  0 46 46 13 46 46 46 46 46 46]
45.725
25.3554604572664
[62  3 24 39 29  4  7 60  9 59]
[ 3  3 39 39  4  4 60 60 59 59]


### Exercise 5 Data types

(1) Create a NumPy array of 10 random integers from 0-100.

(2) Calculate the mean, which will be a float.

(3) Create an array of type float based on it, and replace the
    outliers (i.e., \<mean-std or >mean+std) with the mean.

(4) Create a NumPy array of 20 random floats from 0-100.

(5) Replace those numbers whose int portion is even with the mean.
    (So 20.5 would be replaced, but 21.5 would not be.)

In [180]:
arr = np.random.randint(0, 100, 10)
print(arr)

# mean
arrMean = arr.mean()
print(arrMean)
print(arr)

# typecast to float -- new array
arr2 = arr.astype(np.float32)
print(arr2)

# remove outliers
arr2[(arr2 < (arr2.mean() - arr2.std())) |
     (arr2 > (arr2.mean() + arr2.std()))] = arr2.mean()
print(arr2)

# new array of 20 random float numbers
arr3 = np.random.rand(20) * 100
print(arr3)

# replace numbers with even int part with mean
arr3[arr3.astype(np.int32)%2==0] = arr3.mean()
print(arr3)

[35 52 44 21 85 76 39 53 29 78]
51.2
[35 52 44 21 85 76 39 53 29 78]
[35. 52. 44. 21. 85. 76. 39. 53. 29. 78.]
[35.  52.  44.  51.2 51.2 51.2 39.  53.  51.2 51.2]
[56.78439614 40.40087796 88.59049207 56.68406548 98.25473442  8.48978851
  6.89606277  3.53835566 63.45819962 54.44392831 98.31594137  9.59922436
 84.80439848 53.71009972 26.65555979 64.34152663 52.28165425 94.40410825
 39.53880606 84.44882926]
54.28205245547787
[54.28205246 54.28205246 54.28205246 54.28205246 54.28205246 54.28205246
 54.28205246  3.53835566 63.45819962 54.28205246 54.28205246  9.59922436
 54.28205246 53.71009972 54.28205246 54.28205246 54.28205246 54.28205246
 39.53880606 54.28205246]


### Exercise 6 nan

(1) Create a NumPy array of 30 random ints from 0-1000.

(2) Find the numbers that are \<mean-std or >mean+std, and set them to
    be nan

(3) Now change those nan values to be the mean of the array's
    elements.

In [243]:
arr = np.random.randint(0, 1000, 30)
arrMean = arr.mean()
arrStd = arr.std()

arr = arr.astype(np.float64)
print(arr)

# setting numbers to NaN
arr[(arr < (arr.mean()-arr.std())) |
    (arr > (arr.mean()+arr.std()))] = np.nan
print(arr)

# change nan values to mean
arr[np.isnan(arr)] = arr[~np.isnan(arr)].mean()
print(arr)

# # back to int
arr = arr.astype(np.int64)
print(arr)


[673. 437. 209. 901. 431. 906. 909. 419. 209.  46. 384. 905. 344. 958.
 635. 222. 288. 993.  83. 479. 780. 348.  11. 504. 137. 986. 779. 103.
 501. 528.]
[673. 437. 209.  nan 431.  nan  nan 419. 209.  nan 384.  nan 344.  nan
 635. 222. 288.  nan  nan 479. 780. 348.  nan 504.  nan  nan 779.  nan
 501. 528.]
[673.         437.         209.         453.88888889 431.
 453.88888889 453.88888889 419.         209.         453.88888889
 384.         453.88888889 344.         453.88888889 635.
 222.         288.         453.88888889 453.88888889 479.
 780.         348.         453.88888889 504.         453.88888889
 453.88888889 779.         453.88888889 501.         528.        ]
[673 437 209 453 431 453 453 419 209 453 384 453 344 453 635 222 288 453
 453 479 780 348 453 504 453 453 779 453 501 528]


### Exercise 7 Multidimensional NumPy

(1) Create a 2-dimensional NumPy array of 45 random integers, from 0-100.

(2) Retrieve the elements at row index 2.

(3) Retrieve the elements at column index 3.

(4) Retrieve the elements at row indexes 1 and 4.

(5) Retrieve the elements at column indexes 1 and 4.

(6) Get the mean of the even numbers in row index 4.

(7) Get the mean of the odd numbers in column index 4.

In [222]:
arr = np.random.randint(0, 100, 45)
print(arr)

# multidimensional
arr.shape = (9, 5)
print(arr)

# elements at row 2
print(arr[2])

# elements at column 3
print(arr[:, 3])

# elements at row 1 to 4
print(arr[[1,4], :])

# elements at column 1 to 4
print(arr[:, [1,4]])

# mean of even numbers at row index 4
fourthMean = arr[4][arr[4] % 2 == 0].mean()
print(fourthMean)

# mean of odd numbers at column index 4
fourthColMean = arr[:, 4][arr[:, 4] % 2 != 0].mean()
print(fourthColMean)


[70 99 86  6 75 16 88 63 93 19  7 46 33 95 28  5 79 95 24 61 41 30 23 77
 33  4 83 25 59  2 14 84 82 60  5 65 78 73 26 31 76 57 18  8 34]
[[70 99 86  6 75]
 [16 88 63 93 19]
 [ 7 46 33 95 28]
 [ 5 79 95 24 61]
 [41 30 23 77 33]
 [ 4 83 25 59  2]
 [14 84 82 60  5]
 [65 78 73 26 31]
 [76 57 18  8 34]]
[ 7 46 33 95 28]
[ 6 93 95 24 77 59 60 26  8]
[[16 88 63 93 19]
 [41 30 23 77 33]]
[[99 75]
 [88 19]
 [46 28]
 [79 61]
 [30 33]
 [83  2]
 [84  5]
 [78 31]
 [57 34]]
30.0
37.333333333333336


### Exercise 8 More Multidimensional

(1) Create a 6x6 NumPy array with random integers from 0-100.

(2) What is the mean of each column?

(3) Replace all even numbers in the array with twice their values. (So
    20 will become 40, and 40 will become 80.)

(4) Once again, calculate the mean of each column

(5) Now transpose the array and calculate the mean of each row.  Is it
    the same as you got before?

(6) Now sort each of the columns in the transposed array.  What does
    it look like now?

In [244]:
arr = np.random.randint(0, 100, 36).reshape(6,6)
print(arr)

# mean of each column
meanArr = arr.mean(axis=0)
print(meanArr)
print("\n")

# replace all even with double
arr[arr%2==0] = arr[arr%2==0]*2
print(arr)

# mean of each column
meanArr1 = arr.mean(axis=0)
print(meanArr1)
print("\n")

# transpose array and mean of each row
arr = arr.T
print(arr)
meanRows = arr.mean(axis=1)
print(meanRows)
# mean of columns = mean of rows after transposing

# sort columns in transposed array
arr.sort(axis=0)
print(arr)

[[11 65 53 76 35 19]
 [88 15 15 95 90 14]
 [41 75 60 64 99 72]
 [46 13  6 83 45 57]
 [61 43 78 68 87 49]
 [27 52 96 43 78 47]]
[45.66666667 43.83333333 51.33333333 71.5        72.33333333 43.        ]


[[ 11  65  53 152  35  19]
 [176  15  15  95 180  28]
 [ 41  75 120 128  99 144]
 [ 92  13  12  83  45  57]
 [ 61  43 156 136  87  49]
 [ 27 104 192  43 156  47]]
[ 68.          52.5         91.33333333 106.16666667 100.33333333
  57.33333333]


[[ 11 176  41  92  61  27]
 [ 65  15  75  13  43 104]
 [ 53  15 120  12 156 192]
 [152  95 128  83 136  43]
 [ 35 180  99  45  87 156]
 [ 19  28 144  57  49  47]]
[ 68.          52.5         91.33333333 106.16666667 100.33333333
  57.33333333]
[[ 11  15  41  12  43  27]
 [ 19  15  75  13  49  43]
 [ 35  28  99  45  61  47]
 [ 53  95 120  57  87 104]
 [ 65 176 128  83 136 156]
 [152 180 144  92 156 192]]
